  version: '3'

  services:
    postgres:
      image: postgres
      container_name: my-postgresql-database-container-1
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=asdasd
        - POSTGRES_DB=data
